package com.desenvolvimento.logica.cashpilot_api.auth.model;

public enum AuthEventType {
    PASSWORD_CHECK,
    MFA_CHECK,
    LOGIN_COMPLETED,

    TEMPORARY_LOCK_APPLIED,
    ACCOUNT_BLOCKED,
    ACCOUNT_UNBLOCKED,
    ACCOUNT_UNLOCKED,

    LOGOUT,
    SESSION_REVOKED,

    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,

    MFA_ENABLED,
    MFA_DISABLED,
    MFA_RECOVERY_CODE_USED,

    EMAIL_VERIFICATION_REQUESTED,
    EMAIL_VERIFICATION_COMPLETED,

    TENANT_SELECTED,
    ACCESS_DENIED
}
